#pragma once

#include <Arduino.h>

// =============================================================================
// WEIGH_STACK.H - Local weigh stack (LIFO), RAM only, not persistent
// =============================================================================
// Stores individual ingredient weights pushed via ENTER key.
// Stack resets on TARE (new session) or CLEAR long press.
// Lost on reboot — this is correct behavior.

namespace WeighStack {

static const int MAX_ITEMS = 50;
static const size_t UUID_CAP = 37;
static const size_t SESSION_ID_CAP = 65;
static const size_t RESPONSE_ID_CAP = 25;

struct Entry {
  float grams;
  long oldOffset;
  long oldZt;
  uint32_t productId;
  char uuid[UUID_CAP];
  char sessionId[SESSION_ID_CAP];
  char confirmResponseId[RESPONSE_ID_CAP];
};

// Push a weight onto the stack. Returns true if pushed, false if full.
bool push(float grams);

// Push a reversible weighing commit. Remote metadata may be empty for local or
// legacy commits; a response ID is attached after the MQTT response is staged.
bool pushCommit(float grams, long oldOffset, long oldZt,
                const char* uuid, uint32_t productId, const char* sessionId);

// Attach the confirm receipt generated by MQTT to the newest entry.
bool setLastConfirmResponseId(const char* responseId);

// Read the newest entry without removing it. Null when empty.
const Entry* peek();

// Pop the last weight from the stack. Returns true if popped, false if empty.
bool pop();

// Clear the entire stack.
void clear();

// Get the sum of all weights in the stack.
float total();

// Get the number of items in the stack.
int count();

// Get a specific item by index (0 = oldest, count-1 = newest).
// Returns 0.0 if index is out of range.
float get(int index);

// Reference offset (raw counts at the time of manual TARE)
void   setReferenceOffset(long rawOffset);
long   getReferenceOffset();
bool   hasReference();
void   clearReference();

} // namespace WeighStack
